include:
  - ./docker-compose.observability.yml

services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .vali.env

  dbmate:
    image: amacneil/dbmate
    volumes:
      - ./validator/db:/db
    command: --wait up
    env_file:
      - .vali.env
    networks:
      - postgres_network
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable}
      DBMATE_WAIT_TIMEOUT: 60s

  redis:
    image: redis/redis-stack:latest
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:


networks:
  postgres_network:
  redis_network:
