datasets:
    path: 'path/to/your/test/dataset'
    type: 'your_dataset_type'

sequence_len: 4096
batch_size: 1
output_dir: 'outputs/'
val_set_size: 0
device: 'cuda'

do_train: false
do_eval: true
evaluation_strategy: "steps"
eval_steps: 100
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true
gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1

max_consecutive_nans: 5
max_nan_percentage: 5
starting_batch_size: 1
log_interval_seconds: 10
