auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  # must be enabled to delete logs after the retention_period
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  retention_period: 168h  # 7d
  allow_structured_metadata: true

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
