global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: otel-collector-self
    static_configs:
      - targets:
        - otel-collector:8888

  - job_name: otel-collector-services
    static_configs:
      - targets:
        - otel-collector:9090
